// content/apps/*.md を読んで server/utils/_readmes-generated.ts を生成する。
// Nitro の serverAssets はモジュール構成や @nuxt/content の都合で挙動が安定しないので、
// ビルド時に TypeScript にインライン化して runtime 依存をなくす。
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..')
const inDir = resolve(root, 'content', 'apps')
const outFile = resolve(root, 'server', 'utils', '_readmes-generated.ts')

const items = []
for (const name of readdirSync(inDir).sort()) {
  if (!name.endsWith('.md')) continue
  const slug = name.replace(/\.md$/, '')
  const raw = readFileSync(resolve(inDir, name), 'utf8')
  items.push({ slug, raw })
}

mkdirSync(dirname(outFile), { recursive: true })

const body =
  `// AUTO-GENERATED by scripts/build-readmes.mjs — do not edit by hand.\n` +
  `// Re-runs on \`npm run build\` / \`npm run dev\` (prebuild / predev).\n` +
  `export interface RawReadme { slug: string; raw: string }\n` +
  `export const RAW_README_FILES: RawReadme[] = ${JSON.stringify(items, null, 2)}\n`

writeFileSync(outFile, body)
console.log(`wrote ${items.length} readme(s) → server/utils/_readmes-generated.ts`)
